implement a Transport.Close that waits for the reuse's GC to finish
libp2p/go-libp2p-quic-transport pull request #211
Opened 2021-07-07 19:15 UTC by marten-seemann

This finally makes it possible to run tests with race detector, and therefore switch to the Unified CI Setup.

Not sure if the implementation of `Transport.Close` here is sufficient to fix #176 though.

2021-07-08 03:46 UTC, Stebalien requested changes

2021-07-08 03:46 UTC, Stebalien commented on reuse.go
> +		<-r.garbageCollectorStopChan
This can deadlock if we're waiting for the garbage collection routine to take the lock.

2021-07-17 09:17 UTC, marten-seemann commented
I removed the rather complicated logic of starting and stopping the reuse gc function. Now that we have a clean shutdown procedure, this won't be necessary any more.

2021-07-19 19:17 UTC, Stebalien requested changes
> I removed the rather complicated logic of starting and stopping the reuse gc function. Now that we have a clean shutdown procedure, this won't be necessary any more.

We're still stopping the garbage collector when we have no more connections. We need to remove that if we're going to remove the auto start/stop feature.

2021-07-19 20:20 UTC, marten-seemann commented
> We're still stopping the garbage collector when we have no more connections. We need to remove that if we're going to remove the auto start/stop feature.

Oops, must have missed that. Fixed.

2021-07-19 22:20 UTC, Stebalien approved these changes

2021-07-19 22:20 UTC, Stebalien commented
LGTM but there's a test failure we should probably investigate.

2021-07-20 09:45 UTC, marten-seemann commented
> LGTM but there's a test failure we should probably investigate.

Looks unrelated, I opened #213.

2021-07-20 18:30 UTC, merged